In [43]:
import pandas as pd
df = pd.read_csv("/content/ventas.csv")

In [44]:
df.head(-3)

,fecha,id_cliente,producto,categoria,ciudad,unidades,precio_unitario,descuento,canal,ventas
0,2025-11-03,13375,Guantes gym,Deportes,Bogota,4,48100.0,0.05,En linea,182780.0
1,2025-06-05,19441,Licuadora,Hogar,Barranquilla,5,81800.0,0.00,Tienda,409000.0
2,2025-06-02,10603,Tapete yoga,Deportes,Bogota,2,75200.0,0.10,En linea,135360.0
3,2025-11-15,10698,Bicicleta estatica,Deportes,Bogota,3,42300.0,0.00,Tienda,126900.0
4,2025-08-29,15539,Tenis urbanos,Moda,Cali,1,94500.0,0.05,Tienda,89775.0
...,...,...,...,...,...,...,...,...,...,...
4812,2025-11-02,10210,Bicicleta estatica,Deportes,Medellin,2,32500.0,0.30,En linea,45500.0
4813,2025-04-23,12616,Chaqueta impermeable,Moda,Medellin,2,31800.0,0.15,Tienda,54060.0
4814,2025-07-18,11960,Jean slim,Moda,Barranquilla,4,30100.0,0.20,Tienda,96320.0
4815,2025-01-13,12522,Mancuernas 5kg,Deportes,bogota,3,40900.0,0.00,Tienda,122700.0
4816,2025-02-18,18487,Set de sabanas,Hogar,Medellin,2,48800.0,0.20,En linea,78080.0

In [45]:
df.shape

(4820, 10)

In [46]:
df.columns

Index(['fecha', 'id_cliente', 'producto', 'categoria', 'ciudad', 'unidades',
       'precio_unitario', 'descuento', 'canal', 'ventas'],
      dtype='object')

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4820 entries, 0 to 4819
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            4820 non-null   object
 1   id_cliente       4820 non-null   int64
 2   producto         4820 non-null   object
 3   categoria        4820 non-null   object
 4   ciudad           4820 non-null   object
 5   unidades         4820 non-null   int64
 6   precio_unitario  4820 non-null   float64
 7   descuento        4702 non-null   float64
 8   canal            4820 non-null   object
 9   ventas           4796 non-null   float64
dtypes: float64(3), int64(2), object(5)
memory usage: 376.7+ KB

In [50]:
df["fecha"] = pd.to_datetime(df["fecha"])

In [49]:
df['producto']=df['producto'].astype(str)
df['categoria']=df['categoria'].astype(str)
df['ciudad']=df['ciudad'].astype(str)
df['canal']=df['canal'].astype(str)

In [54]:
type(df)

pandas.core.frame.DataFrame

In [55]:
type(df['ciudad'])

pandas.core.series.Series

In [56]:
type(df['ciudad'][0])

str

In [52]:
df.dtypes

fecha              datetime64[ns]
id_cliente                  int64
producto                   object
categoria                  object
ciudad                     object
unidades                    int64
precio_unitario           float64
descuento                 float64
canal                      object
ventas                    float64
dtype: object

In [32]:
df['fecha'].unique()

<DatetimeArray>
['2025-11-03 00:00:00', '2025-06-05 00:00:00', '2025-06-02 00:00:00',
 '2025-11-15 00:00:00', '2025-08-29 00:00:00', '2025-03-04 00:00:00',
 '2025-08-23 00:00:00', '2025-07-08 00:00:00', '2025-09-11 00:00:00',
 '2025-08-14 00:00:00',
 ...
 '2025-06-01 00:00:00', '2025-01-28 00:00:00', '2025-12-28 00:00:00',
 '2025-05-22 00:00:00', '2025-06-09 00:00:00', '2025-04-16 00:00:00',
 '2025-11-25 00:00:00', '2025-07-04 00:00:00', '2025-07-29 00:00:00',
 '2025-02-02 00:00:00']
Length: 365, dtype: datetime64[ns]

In [24]:
df["categoria"].unique()

array(['Deportes', 'Hogar', 'Moda', 'Tecnologia'], dtype=object)

In [25]:
df["ciudad"].unique()

array(['Bogota', 'Barranquilla', 'Cali', 'Medellin', 'MEDELLIN', 'bogota'],
      dtype=object)

In [26]:
df["canal"].unique()

array(['En linea', 'Tienda'], dtype=object)

In [27]:
df["producto"].nunique()

20

In [28]:
df["id_cliente"].nunique()

3874